add_executable(App WIN32 "src/network_layer.cc" "src/main.cc" "src/chat_app.cc" "include/app/chat_app.h" "include/app/network_layer.h" "include/app/network_events.h")
add_executable(Server "src/server.cc")
add_definitions(-DWIN32_LEAN_AND_MEAN)
target_include_directories(App PRIVATE "include/")
target_link_libraries(App PUBLIC Engine NetworkCore)
target_include_directories(Server PRIVATE "include/")
target_link_libraries(Server PUBLIC NetworkCore Engine)